### ISSUE TITLE
Convention based mappings

### ISSUE THREAD

**Issue by npehrsson** [daverix/slingerORM#2]
Is there a possibility that convention based mapping can be added, so insteda of having an attribute on those who should be mapped, add an attribute if it should be ignored or have an different column name.

**Comment by daverix** [comment]
Yes it already supports setting transient on a field or annotate it with ```@NotDatabaseField```. Otherwise it will try to map all the fields in the class that is annotated with ```@DatabaseEntity```.

**Comment by npehrsson** [comment]
Good
