### ISSUE TITLE
Mapping fields

### ISSUE THREAD

**Issue by npehrsson** [daverix/slingerORM#3]
Is it not better to map fields than methods?
What happens if I want a readonly on my entity, then I will not have an setMethod, or if I do not want to have all my private fields visible.

Or I just simply want to bypass validations or other logic on get/sets

**Comment by daverix** [comment]
Right now it looks at the fields, if it cannot access the field directly it looks for setters and getters. If the fields have other naming that standard it looks for setters and getters annotated with ```@SetField``` and ```@GetField```. If it can't find any of those methods it will produce an error at compile time.

Do you want it to not produce an error and instead ignore the field?

**Comment by npehrsson** [comment]
Do you mean if it is public? Can it not access a field that is private?
Is it possible to access private fields in Java with reflection? Even if there is a small performance loss by using reflection, if it is cached and not "searching for a property" it is quite fast in .net at least, and the code will be much better.

**Comment by daverix** [comment]
No it cannot access a private field because it uses generated code for performance reasons. I will not add any reflection to this library.

**Comment by npehrsson** [comment]
Will it really be that slow?

**Comment by daverix** [comment]
I haven't made any performance tests, but why do you want to access private fields? You can create interfaces for your object if you want to only use getters and not setters or the other way around.  I don't think the code will be much better using reflection. It only becomes harder to understand. By generating source code you will also be able to see every step when you debug etc. It will also work out of the box when using Proguard (obfuscate code in Java/Android). With reflection you get the problem of fields changing name.

**Comment by npehrsson** [comment]
I disagree, if I have created an Order for example, then I probably want
the Order Created date to be readonly and be set in the constructor. But
there are now way to support that in a clean way without the approach I am
talking about.
I can see your point on obfuscate

**Comment by daverix** [comment]
The approach I suggested is this:

```
interface ObjectToUseSomewhere {
    Date getCreated();
    ...
}

@DatabaseEntity
public class MyEntity implements ObjectToUseSomewhere {
    ...
}

@DatabaseStorage
public interface MyEntityStorage {
    @Select(where = "id = ?")
    MyEntity getMyEntity(SQLiteDatabase db, long id);
}

SQLiteDatabase db = ...
ObjectToUseSomewhere obj = storage.getMyEntity(db, 42);
// only possible to use things in interface...
```

To limit the object itself. you can create another constructor that you can use to use only when inserting entities. We could do something like annotate the parameters of the constructor to tell SlingerORM how to use it to get what you want maybe? It then requires SlingerORM to create a new instance of the object in the mapper and not in the storage implementation.
